# docker-compose.yml
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "pank"
      POSTGRES_PASSWORD: "example"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      POSTGRES_USER: "pank"
      POSTGRES_PASSWORD: "example"
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
